#!/bin/bash

command -v kubectl && (
    kubectl describe secret -n kube-system $(kubectl get secrets -n kube-system | grep kuboard-user | awk '{print $1}')  | grep -E '^token'
) || (
    echo "you should install kubectl"
)