#!/bin/bash

getbin=$1

echo "will download $getbin"

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

if command_exists docker && [ -e /var/run/docker.sock ]; then
    docker pull registry.cn-beijing.aliyuncs.com/k7scn/kubetools
    docker run -it --rm -v /tmp/kubetools:/root registry.cn-beijing.aliyuncs.com/k7scn/kubetools cp -a /root/bin/$getbin /root/$getbin
    mv /tmp/kubetools/$getbin /usr/local/bin/$getbin
    chmod +x /usr/local/bin/$getbin
fi
