#!/bin/bash

if [ -f "/etc/kubernetes/pki/etcd/ca.crt" ];then
  etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/peer.crt --key=/etc/kubernetes/pki/etcd/peer.key $@
else
  etcdctl $@
fi
