#!/bin/bash

command -v kubectl && (
    kubectl describe secret -n kube-system $(kubectl get secrets -n kube-system | grep dashboard-admin | cut -f1 -d ' ') | grep -E '^token'
) || (
    echo "you should install kubectl"
)