#!/bin/bash

set -x

image="ysicing/tools"

curl -s  https://api.ip.sb/geoip | grep China -q && (
	image="registry.cn-beijing.aliyuncs.com/k7scn/tools"
) || (
	image="ysicing/tools"
)

docker pull ${image}

docker run --rm -v /usr/local/bin:/sysdir ${image} tar zxf /pkg.tgz -C /sysdir
