#!/bin/bash

set -x

action() {
	image=$1
	docker pull ${image}
	docker run --rm -v /usr/local/bin:/sysdir ${image} tar zxf /pkg.tgz -C /sysdir
}

curl -s  https://api.ip.sb/geoip | grep China -q && (
	action "registry.cn-beijing.aliyuncs.com/k7scn/tools"
) || (
	action "ysicing/tools"
)
